### ISSUE TITLE
Add `john` format option

### ISSUE THREAD

**Issue by rbsec** [ShutdownRepo/targetedKerberoast#12]
Although the username is embedded in the `$krb5tgs$` "hash", tools like John aren't able to parse it out. This means when you try and crack them or show the output, no usernames are listed, which makes matching up the cracked passwords to the users more of a pain:

```
$  john kerb.txt
[...]
Password1        (?)
[...]

$ john kerb.txt --show
?:Password1
```

John's expecting the them to have the username at the start followed by a colon - something like:

```
Username:$krb5tgs$23$*Username$TEST.LOCAL$test.local/Username*$90[...]3$3[...]
```

And then you get the usernames listed in the output:

```
$ john kerb.txt --show
Username:Password1
```

If there are other tools that don't want this (and just want the "hash", then perhaps this could be an output format option? Some of the Impacket tools have different flags for john and hashcat output (for instance) - so that could be a workaround to preserve both behaviours.

**Comment by ShutdownRepo** [comment]
Agreed, it would be nice to have the format option (hashcat or john) in CLI args.
I won't have the time to implement it at the moment, but if someone wants to bring that in a PR, I'll be happy to review & merge

**Comment by rbsec** [comment]
@ShutdownRepo thanks - I've submitted a pull request (#13) with a proposed change.
